/* Generated by gallery/scripts/fetch-showpieces.mjs - do not edit by hand. */
import type { ReactNode } from "react";

import { Demo3dCard } from "./Demo3dCard";
import { DemoSpotlight } from "./DemoSpotlight";
import { DemoBackgroundBeams } from "./DemoBackgroundBeams";
import { DemoMarquee } from "./DemoMarquee";
import { DemoShimmerButton } from "./DemoShimmerButton";
import { DemoMeteors } from "./DemoMeteors";
import { DemoAnimatedShinyText } from "./DemoAnimatedShinyText";
import { DemoDock } from "./DemoDock";
import { DemoBlurText } from "./DemoBlurText";
import { DemoCountUp } from "./DemoCountUp";
import { DemoDecryptedText } from "./DemoDecryptedText";
import { DemoMatrixText } from "./DemoMatrixText";
import { DemoGlobe } from "./DemoGlobe";
import { DemoAurora } from "./DemoAurora";
import { DemoParticlesWebgl } from "./DemoParticlesWebgl";
import { DemoHyperspeed } from "./DemoHyperspeed";
import { DemoSplashCursor } from "./DemoSplashCursor";
import { DemoShaderLensBlur } from "./DemoShaderLensBlur";
import { DemoCobeGlobeInteractive } from "./DemoCobeGlobeInteractive";
import { DemoLetterGlitch } from "./DemoLetterGlitch";
import { DemoCanvasFractalGrid } from "./DemoCanvasFractalGrid";
import { DemoTextureCard } from "./DemoTextureCard";

/** Live demos wrap the actually-fetched component (only render when available). */
export const LIVE_DEMOS: Record<string, () => ReactNode> = {
  "3d-card": Demo3dCard,
  "spotlight": DemoSpotlight,
  "background-beams": DemoBackgroundBeams,
  "marquee": DemoMarquee,
  "shimmer-button": DemoShimmerButton,
  "meteors": DemoMeteors,
  "animated-shiny-text": DemoAnimatedShinyText,
  "dock": DemoDock,
  "blur-text": DemoBlurText,
  "count-up": DemoCountUp,
  "decrypted-text": DemoDecryptedText,
  "matrix-text": DemoMatrixText,
};

/** Static previews are self-contained CSS/SVG approximations (render whenever listed). */
export const STATIC_PREVIEWS: Record<string, () => ReactNode> = {
  "globe": DemoGlobe,
  "aurora": DemoAurora,
  "particles-webgl": DemoParticlesWebgl,
  "hyperspeed": DemoHyperspeed,
  "splash-cursor": DemoSplashCursor,
  "shader-lens-blur": DemoShaderLensBlur,
  "cobe-globe-interactive": DemoCobeGlobeInteractive,
  "letter-glitch": DemoLetterGlitch,
  "canvas-fractal-grid": DemoCanvasFractalGrid,
  "texture-card": DemoTextureCard,
};
